### ISSUE TITLE
signcolumn=no have problems with vim-gitgutter

### ISSUE THREAD

**Issue by ysolis** [sheerun/vimrc#3]
The plugin vim-gitgutter (https://github.com/airblade/vim-gitgutter) use the signcolumn to show differences with vim original file (differences, deleted and added lines)

vimrc disables fully signcolumn with neovim 0.4.3 (i imagine for a vim 8.x backport) and i need to enable manually signcolumn to see the differences.

maybe one setting to don't disable signcolumn can be of help or ... integrate plugin with vim-gitgutter ...

**Comment by sheerun** [comment]
Thanks for noticing. I'm leaving the default `auto` for old vim now

**Comment by sheerun** [comment]
btw. It would be very nice if neovim implemented signcolumn=number, maybe you can notice them in their issue tracker
